version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: workorbit_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: WorkOrbit
      POSTGRES_USER: sanjeev
      POSTGRES_PASSWORD: sanjeev
    volumes:
      - workorbit_postgress_data:/var/lib/postgresql/data

volumes:
  workorbit_postgress_data:
